---

template: |
  $CHANGES

categories:
  - title: "Security fixes:"
    labels:
      - "bundler: security fix"

  - title: "Breaking Changes:"
    labels:
      - "bundler: breaking change"

  - title: "Major enhancements:"
    labels:
      - "bundler: major enhancement"

  - title: "Deprecations:"
    labels:
      - "bundler: deprecation"

  - title: "Features:"
    labels:
      - "bundler: feature"

  - title: "Performance:"
    labels:
      - "bundler: performance"

  - title: "Documentation:"
    labels:
      - "bundler: documentation"

  - title: "Minor enhancements:"
    labels:
      - "bundler: minor enhancement"

  - title: "Bug fixes:"
    labels:
      - "bundler: bug fix"

change-template: "  - $TITLE [#$NUMBER]($URL)"

no-changes-template: "  No changes."

include-labels:
  - "bundler: security fix"
  - "bundler: breaking change"
  - "bundler: major enhancement"
  - "bundler: deprecation"
  - "bundler: feature"
  - "bundler: performance"
  - "bundler: documentation"
  - "bundler: minor enhancement"
  - "bundler: bug fix"
